version: '3.1'

services:
  django:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    volumes:
      - .:/app:z
    init: true
    environment:
      DJANGO_SETTINGS_MODULE: "config.settings.local"
      SECRET_KEY: local_dev_secret_key
      SECURE_SSL_REDIRECT: "false"
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    # do nothing forever - exec commands elsewhere
    command: tail -f /dev/null

  docs:
    image: ds_judgements_public_ui_local_docs
    container_name: ds_judgements_public_ui_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./ds_judgements_public_ui:/app/ds_judgements_public_ui:z
    ports:
      - "7000:7000"
    command: /start-docs

networks:
  default:
    external:
      name: caselaw
